## Curry jamaïcain 

La recette originale est disponible [ici](https://www.simplyrecipes.com/recipes/jamaican_goat_curry/).

### Ingrédients 

- 1/4 tasse d'huile (coco)
- 6 à 8 tbs poudre de curry 
- 1 tbs allspice
- 3 lbs goat meat (épaule d'orignal)
- Sel
- 1 gros oignon ou 2 oignons medium hachés
- 2 piments forts hachés
- gingembre haché, ~2po
- 1-2 cannes (15oz) de lait de coco
- 1 canne (15oz) sauce tomate ou tomates broyées
- 2-3 têtes d'ail
- 3-4 tasses d'eau 
- 2-3 carottes pelées et 
- 8-10 patates

### Préparation

- Cut and prepare everything
- Make the curry powder: If you can find Jamaican curry powder, definitely use it. If not, use regular curry powder and add the allspice to it. You will need at least 6 tablespoons of spices for this stew, and you can kick it up to 8-9 depending on how spicy you like it.
- Cut and salt the goat meat: Cut the meat into large chunks, maybe 2-3 inches across. If you have bones, you can use them, too. Salt everything well and set aside to come to room temperature for about 30 minutes.
- Heat the curry powder in oil: Heat the oil in a large pot over medium-high heat. Mix in 2 tablespoons of the curry powder and heat until fragrant.
- Brown meat in curried oil: Pat the meat dry and brown well in the curried oil. Do this in batches and don’t overcrowd the pot. It will take a while to do this, maybe 30 minutes or so. Set the browned meat aside in a bowl. (When all the meat is browned, if you have bones, add them and brown them, too.)
- Cook onions, habanero, ginger, garlic, carrots: Add the onions and habanero to the pot and sauté, stirring from time to time, until the onions just start to brown, about 5 minutes. Sprinkle some salt over them as they cook. Add the ginger and garlic, mix well and sauté for another 1-2 minutes.
- Put the meat (and bones, if using) back into the pot, along with any juices left in the bowl. Mix well.
- Add coconut milk, tomatoes, curry powder, water, thyme, then simmer: Pour in the coconut milk and tomatoes and 5 tablespoons of the curry powder. Stir to combine. If you are using 2 cans of coconut milk, add 3 cups of water. If you’re only using 1 can, add 4 cups of water. Add the thyme.
- Bring to a simmer and let it cook until the meat is falling-apart tender, which will take at least 2 hours. Longer if you have a mature goat.
- Add potatoes: Once the meat is close to being done – tender but not falling apart yet – Add the potatoes and mix in. The stew is done when the potatoes are. Taste for salt and add some if it needs it.
- Skim fat: You might need to skim off the layer of fat at the top of the curry before serving. Do this with a large, shallow spoon, skimming into a bowl. Also, be sure to remove any bones before you serve the curry.
- The stew is better the day after, or even several days after, the day you make it.
- Serve with Jamaican rice and peas, a coconut rice with kidney beans.

