## Kolaches

Voir [ici](https://www.allrecipes.com/recipe/268998/texas-sausage-kolaches-klobasneks/) pour la recette originale

### Ingrédients

- 1/2 tasse lait
- 1/4 tasse sucre
- 1 tsp sucre
- 1/4 tasse beurre
- .5 ounce active dry yeast (~1.65 tbsp)
- 1/2 tasse eau chaude
- 2 oeufs battus
- 4 1/2 tasse farine
- recette à stuffer dedans! (comme le fois ou pâté au port)

### Préparation

- Heat milk in a small saucepan over medium heat until it begins to bubble. Remove from heat immediately. Stir sugar, salt, and 1/4 cup butter into the milk and stir until sugar is dissolved. Set aside to cool to room temperature, about 10 minutes.

- Combine warm water and yeast in the large bowl of a stand mixer and stir until dissolved. Stir in cooled milk mixture, eggs, and 2 cups flour. Beat using the dough hook attachment until smooth. Add remaining flour, mixing as you go, just until dough is elastic and slightly stiff, but not dry.

- Turn dough out onto a floured board and knead until smooth and very elastic, 10 to 15 minutes. Coat dough lightly with butter or oil and place in a bowl. Cover with plastic wrap or a damp towel and let sit in a warm place to double in size, about 1 hour.

- Preheat the oven to 350 degrees F (175 degrees C). Lightly oil a baking sheet.

- Turn risen dough out onto a very lightly floured board. Roll into a log, cut into 5 equal pieces, and cut each piece into quarters to make 20 equal-sized pieces of dough. Use the palm of your hand to flatten and press 1 piece into a circle or oval. Place the circle on the board and add 1 piece of Cheddar cheese topped with 1 dry halved sausage. Roll dough around fillings and very tightly pinch all seams together to seal. Smooth seams down and place kolache on the prepared baking sheet. Repeat with remaining dough and filling to make 20 kolaches.

- Bake in the preheated oven until golden, 12 to 15 minutes.
