## Pâté au poulet

Cette recette couvre uniquement la garniture pour le pâté au poulet. La recette originale est disponible [ici](https://www.ricardocuisine.com/recettes/5548-pate-au-poulet-le-meilleur).

### Ingrédients

- 6 tbsp beurre ramolli
- 1/4 tasse farine
- 1 tbsp f/cule de maïs
- 1/2 tasse lait
- oignon (1) haché finement
- carotte (1) pelée et coupée en dés
- céleri (1) coupée en dés
- bouillon de poulet concentré (284 ml)
- 1/2 pomme de terre pelée et coupée en dés
- 1 1/2 poulet cuit
- 1/2 tasse petits pois

### Préparation

- Dans un bol, mélanger 55 g (¼ tasse) du beurre avec la farine. Réserver le beurre manié.
- Dans un bol, délayer la fécule dans le lait. Réserver.
- Dans une grande casserole à feu moyen, attendrir l’oignon, la carotte et le céleri dans le reste du beurre. Saler et poivrer. Ajouter le bouillon et la pomme de terre. Porter à ébullition. Couvrir et laisser mijoter 10 minutes ou jusqu’à ce que les légumes soient tendres, mais sans plus. Ajouter le beurre manié et porter à ébullition en remuant délicatement à la cuillère de bois. Ajouter le mélange de lait et de fécule et porter de nouveau à ébullition. Rectifier l’assaisonnement. Incorporer le poulet et les petits pois. Couvrir directement la surface de pellicule plastique. Laisser tiédir le temps de préparer la pâte.
