## Poutine à l'orignal

### Ingrédients 

- 1/4 tasse d'huile (coco)
- 1 tbs poudre de curry 
- 3 lbs épaule d'orignal
- Sel
- 1 gros oignon ou 2 oignons medium hachés
- 2 piments forts hachés
- 1 (15oz) de lait de coco
- 2-3 têtes d'ail
- 3-4 tasses de bouillon de boeuf
- champignons
- 1 oignon vert
- fromage en grain 
- patates douces / régulières
- Thym
- Sauce soya
- Sauce hoisin
- Fécule de maïs

### Préparation

- Cut and prepare everything
- Cut and salt the goat meat: Cut the meat into large chunks, maybe 2-3 inches across. If you have bones, you can use them, too. Salt everything well and set aside to come to room temperature for about 30 minutes.
- Heat the curry powder, other spices, soy and hoisin sauces in oil: Heat the oil in a large pot over medium-high heat. Mix in 1 tablespoon of the curry powder and heat until fragrant.
- Brown meat in curried oil: Pat the meat dry and brown well in the curried oil. Do this in batches and don’t overcrowd the pot. It will take a while to do this, maybe 30 minutes or so. Set the browned meat aside in a bowl. (When all the meat is browned, if you have bones, add them and brown them, too.)
- Cook onions, habanero, garlic, carrots: Add the onions and habanero to the pot and sauté, stirring from time to time, until the onions just start to brown, about 5 minutes. Sprinkle some salt over them as they cook. Add the ginger and garlic, mix well and sauté for another 1-2 minutes.
- Put the meat (and bones, if using) back into the pot, along with any juices left in the bowl. Mix well.
- Add coconut milk, broth, thyme, then simmer. Stir to combine. If you are using 2 cans of coconut milk, add 3 cups of water. If you’re only using 1 can, add 4 cups of water. Add the thyme.
- Bring to a simmer and let it cook until the meat is falling-apart tender, which will take at least 2 hours. Longer if you have a mature goat.
- Prepare sweet potato fries, regular fries or mix of both however you want to make them. I bake them on papier parchemin at 425F for ~45 min, but it would be better with a frier.  
- Thicken the broth with fécule de maïs until desired consistency for the sauce 
- Place fries at the bottom, add cheese, and generously add the sauce with the moose meat. Enjoy! 

