## Soupe thaïe aux crevettes et au lait de coco

### Ingrédients

- 8 champignons shiitakes, les pieds retirés et émincés
- 1 piment jalapeño, épépiné et haché finement
- Sauce au piment fort au goût
- 30 ml (2 c. à soupe) d’huile végétale
- 4 gousses d’ail, hachées
- 30 ml (2 c. à soupe) de gingembre frais haché
- 15 ml (1 c. à soupe) de pâte de tomates
- 15 ml (1 c. à soupe) de poudre de cari
- 10 ml (2 c. à thé) de paprika doux
- 5 ml (1 c. à thé) de cannelle moulue
- 2 boîtes de 398 ml (14 oz) de lait de coco
- 500 ml (2 tasses) de bouillon de poulet
- Bouquets de brocoli
- 2 limes, le zeste râpé finement
- 1/2 lime, pour le jus
- 675 g (1 1/2 lb) de crevettes crues, décortiquées avec ou sans la queue
- 3 oignons verts, émincés en diagonale

### Préparation

1. Dans une grande casserole, dorer les shiitakes avec le piment dans l’huile. Saler et poivrer. Ajouter l’ail, le gingembre, la pâte de tomates, les épices et cuire de 1 à 2 minutes en remuant.
2. Ajouter le lait de coco, le bouillon, les pois mange-tout, le zeste et le jus de lime. Porter à ébullition et laisser mijoter doucement 3 minutes ou jusqu’à ce que les pois mange-tout soient al dente.
3. Ajouter les crevettes et porter de nouveau à ébullition. Poursuivre la cuisson 2 minutes ou jusqu’à ce que les crevettes soient cuites. Rectifier l’assaisonnement. Servir la soupe et garnir d’oignons verts.

### Ressources

- [Recette originale](https://www.ricardocuisine.com/recettes/4907-soupe-thaie-aux-crevettes-et-au-lait-de-coco), merci Ricardo
